from pymongo import MongoClient
DATABASE_IP = "192.168.1.9"
DATABASE_NAME = "TFG"
database = MongoClient(DATABASE_IP)[DATABASE_NAME]

mi_id = "amzn1.ask.account.AETMDJX3CUPAVYCQK6E7G674STKT7CFNLEIO73BEVXCAJ7NTVTPRDFDCVWSJFXTA43ANC2SU2LJYEVXCPR74FSLFTUDJOHDMTWGDV6SQDWF5VDOWBESOCBFPAFMJS7AEAU5EQSHXCT4J6TWI6EHKEICSXYVRGA5AL6ADDQ5K7CMBOP5ICCGSSFUP2Q6UFD4Z5JA5KKOBZQLKVYA"
# try:
#     database['users'].insert_one({
#         "_id": "amzn1.ask.account.AETMDJX3CUPAVYCQK6E7G674STKT7CFNLEIO73BEVXCAJ7NTVTPRDFDCVWSJFXTA43ANC2SU2LJYEVXCPR74FSLFTUDJOHDMTWGDV6SQDWF5VDOWBESOCBFPAFMJS7AEAU5EQSHXCT4J6TWI6EHKEICSXYVRGA5AL6ADDQ5K7CMBOP5ICCGSSFUP2Q6UFD4Z5JA5KKOBZQLKVYA",
#         "titulacion":"master teleco",
#         "curso":1
#     })

# except(Exception):
#     print('Oops')

print(database['users'].find_one(
    {'_id': 123},
    {'_id': False}
))